#!/usr/bin/env python3
"""Generate web/privacy.html (the hosted privacy policy) from the in-app screen.

The in-app PrivacyPolicyScreen is the single source of truth. This script reads
its `_PolicySection(title: ..., body: ...)` string literals and the version /
date / URL facts from assets/data/app_data.json, and writes a static page that
the GitHub Pages deploy serves at https://onica5000.github.io/MHAD/privacy.html
(`flutter build web` copies everything in web/ into build/web/).

  python tool/gen_privacy_html.py          # regenerate
  python tool/gen_privacy_html.py --check  # exit 1 if web/privacy.html is stale

test/unit/privacy_policy_hosted_test.dart fails CI when the page drifts from the
screen, so rerun this after editing the policy copy.
"""

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCREEN = ROOT / "lib" / "ui" / "settings" / "privacy_policy_screen.dart"
APP_DATA = ROOT / "assets" / "data" / "app_data.json"
OUT = ROOT / "web" / "privacy.html"

# One Dart single-quoted or double-quoted literal (no raw/triple strings used).
_LIT = re.compile(r"""'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)\"""")


def _concat_literals(src: str) -> str:
    """Join adjacent Dart string literals and unescape them."""
    out = []
    for m in _LIT.finditer(src):
        raw = m.group(1) if m.group(1) is not None else m.group(2)
        out.append(raw)
    s = "".join(out)
    return (s.replace("\\n", "\n").replace("\\'", "'").replace('\\"', '"')
            .replace("\\$", "$").replace("\\\\", "\\"))


def sections(dart: str):
    pat = re.compile(
        r"_PolicySection\(\s*title:\s*(?P<title>(?:'[^']*'\s*)+),\s*"
        r"body:\s*(?P<body>.*?),\s*headingStyle:", re.S)
    for m in pat.finditer(dart):
        yield _concat_literals(m.group("title")), _concat_literals(m.group("body"))


def _inline(text: str) -> str:
    esc = html.escape(text)
    esc = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", esc)
    return re.sub(r"(https://[^\s()<]+)", r'<a href="\1">\1</a>', esc)


def body_html(body: str) -> str:
    parts = []
    for para in body.split("\n\n"):
        lines = para.split("\n")
        items = [l for l in lines if l.startswith("  - ")]
        head = [l for l in lines if not l.startswith("  - ")]
        if head:
            parts.append("<p>" + "<br>".join(_inline(l) for l in head) + "</p>")
        if items:
            parts.append("<ul>" + "".join(
                f"<li>{_inline(l[4:])}</li>" for l in items) + "</ul>")
    return "\n".join(parts)


def render() -> str:
    data = json.loads(APP_DATA.read_text(encoding="utf-8"))
    facts = {
        "appData.privacyPolicyUrl": data["urls"]["privacyPolicy"],
    }
    dart = SCREEN.read_text(encoding="utf-8")
    secs = list(sections(dart))
    if not secs:
        sys.exit("No _PolicySection found — did the screen's structure change?")
    blocks = []
    for title, body in secs:
        for k, v in facts.items():
            body = body.replace("${" + k + "}", v)
        if "${" in body:
            sys.exit(f"Unresolved interpolation in section {title!r}")
        blocks.append(f"<section>\n<h2>{html.escape(title)}</h2>\n"
                      f"{body_html(body)}\n</section>")
    updated = data["dated"]["privacyPolicyUpdated"]
    version = data["dated"]["privacyPolicyVersion"]
    return f"""<!DOCTYPE html>
<!-- GENERATED by tool/gen_privacy_html.py from
     lib/ui/settings/privacy_policy_screen.dart. Do not edit by hand. -->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Privacy Policy – PA Mental Health Advance Directive</title>
<meta name="description" content="Privacy policy for the PA Mental Health Advance Directive web app.">
<style>
  :root {{ color-scheme: light dark; --fg:#1f2937; --muted:#4b5563; --bg:#ffffff; --accent:#1E3A8A; }}
  @media (prefers-color-scheme: dark) {{ :root {{ --fg:#e5e7eb; --muted:#9ca3af; --bg:#0f172a; --accent:#93c5fd; }} }}
  body {{ margin:0; background:var(--bg); color:var(--fg); font:16px/1.6 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif; }}
  main {{ max-width:720px; margin:0 auto; padding:32px 16px 64px; }}
  h1 {{ font-size:1.6rem; margin:0 0 4px; }}
  h2 {{ font-size:1.15rem; margin:32px 0 8px; }}
  .meta {{ color:var(--muted); margin:0 0 24px; }}
  a {{ color:var(--accent); overflow-wrap:anywhere; }}
  ul {{ padding-left:1.25rem; }}
</style>
</head>
<body>
<main>
<h1>PA MHAD App Privacy Policy</h1>
<p class="meta">Last updated: {html.escape(updated)} ({html.escape(version)}).
The same policy is shown in the app under Settings → Privacy Policy.</p>
{chr(10).join(blocks)}
<p class="meta"><a href="./">Open the app</a></p>
</main>
</body>
</html>
"""


def main():
    page = render()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != page:
            sys.exit("web/privacy.html is stale — run: python tool/gen_privacy_html.py")
        print("web/privacy.html is up to date")
        return
    OUT.write_text(page, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(page)} bytes)")


if __name__ == "__main__":
    main()
